#!/bin/bash

# Install Flutter Pre-commit Hooks

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_color() {
    echo -e "${1}${2}${NC}"
}

print_color $BLUE "🪝 Installing Flutter pre-commit hooks..."

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    print_color $RED "❌ Error: Not in a git repository. Please run this script from the project root."
    exit 1
fi

# Check if scripts directory exists
if [ ! -d "scripts" ]; then
    print_color $RED "❌ Error: scripts directory not found. Please run this script from the project root."
    exit 1
fi

# Check if pre-commit script exists
if [ ! -f "scripts/pre-commit" ]; then
    print_color $RED "❌ Error: scripts/pre-commit file not found."
    exit 1
fi

# Create .git/hooks directory if it doesn't exist
if [ ! -d ".git/hooks" ]; then
    mkdir -p .git/hooks
    print_color $YELLOW "📁 Created .git/hooks directory"
fi

# Function to install hook
install_hook() {
    local hook_name=$1
    local source_script=$2
    local hook_path=".git/hooks/$hook_name"
    
    # Backup existing hook if it exists
    if [ -f "$hook_path" ]; then
        print_color $YELLOW "📋 Backing up existing $hook_name hook"
        mv "$hook_path" "$hook_path.backup.$(date +%s)"
    fi
    
    # Copy and make executable
    cp "$source_script" "$hook_path"
    chmod +x "$hook_path"
    
    print_color $GREEN "✅ Installed $hook_name hook"
}

# Function to create a simple hook wrapper
create_hook_wrapper() {
    local hook_name=$1
    local script_path=$2
    local hook_path=".git/hooks/$hook_name"
    
    cat > "$hook_path" << EOF
#!/bin/bash
# Flutter Git Hook - Auto-generated by install-hooks.sh
# This hook runs the pre-commit script from the scripts directory

SCRIPT_PATH="\$(git rev-parse --show-toplevel)/$script_path"

if [ -x "\$SCRIPT_PATH" ]; then
    exec "\$SCRIPT_PATH" "\$@"
else
    echo "Warning: $script_path not found or not executable"
    exit 0
fi
EOF
    
    chmod +x "$hook_path"
    print_color $GREEN "✅ Created $hook_name hook wrapper"
}

# Function to verify Flutter installation
verify_flutter() {
    if ! command -v flutter &> /dev/null; then
        print_color $YELLOW "⚠️  Warning: Flutter command not found."
        print_color $YELLOW "   Please ensure Flutter SDK is installed and in your PATH."
        print_color $YELLOW "   The hooks will still be installed but may fail during execution."
    else
        local flutter_version=$(flutter --version | head -n 1)
        print_color $GREEN "✅ Flutter found: $flutter_version"
    fi
}

# Function to verify dart installation
verify_dart() {
    if ! command -v dart &> /dev/null; then
        print_color $YELLOW "⚠️  Warning: Dart command not found."
        print_color $YELLOW "   This is usually installed with Flutter SDK."
    else
        local dart_version=$(dart --version)
        print_color $GREEN "✅ Dart found: $dart_version"
    fi
}

# Main installation
main() {
    print_color $BLUE "🔍 Verifying environment..."
    verify_flutter
    verify_dart
    
    print_color $BLUE "\n📦 Installing hooks..."
    
    # Install pre-commit hook
    create_hook_wrapper "pre-commit" "scripts/pre-commit"
    
    print_color $GREEN "\n🎉 Flutter pre-commit hooks installed successfully!"
    print_color $BLUE "\n📋 What happens now:"
    print_color $NC "  • Every commit will automatically format your Dart files"
    print_color $NC "  • Auto-fixable lint issues will be resolved automatically"
    print_color $NC "  • Commits will be blocked if there are unfixable lint errors"
    print_color $NC "  • Generated files will be updated if needed"
    
    print_color $YELLOW "\n💡 Tips:"
    print_color $NC "  • Run 'flutter analyze' to check for issues before committing"
    print_color $NC "  • Use 'dart fix --apply' to fix issues manually"
    print_color $NC "  • The hook only checks staged files for performance"
    
    print_color $BLUE "\n🔧 To uninstall hooks:"
    print_color $NC "  rm .git/hooks/pre-commit"
    
    print_color $GREEN "\nHappy coding! 🚀"
}

# Help message
show_help() {
    echo "Flutter Pre-commit Hook Installer"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help     Show this help message"
    echo "  --uninstall    Remove installed hooks"
    echo ""
    echo "This script installs a pre-commit hook that:"
    echo "  • Formats Dart files with 'dart format'"
    echo "  • Applies automatic fixes with 'dart fix --apply'"
    echo "  • Runs 'flutter analyze' on staged files"
    echo "  • Updates generated files if needed"
    echo "  • Blocks commits if there are unfixable lint errors"
}

# Uninstall function
uninstall_hooks() {
    print_color $YELLOW "🗑️  Uninstalling Flutter pre-commit hooks..."
    
    if [ -f ".git/hooks/pre-commit" ]; then
        rm ".git/hooks/pre-commit"
        print_color $GREEN "✅ Removed pre-commit hook"
    else
        print_color $YELLOW "⚠️  No pre-commit hook found"
    fi
    
    # Restore backups if they exist
    for backup in .git/hooks/*.backup.*; do
        if [ -f "$backup" ]; then
            original="${backup%%.backup.*}"
            mv "$backup" "$original"
            print_color $GREEN "✅ Restored backup: $(basename "$original")"
        fi
    done
    
    print_color $GREEN "🎉 Hooks uninstalled successfully!"
}

# Parse command line arguments
case "${1:-}" in
    -h|--help)
        show_help
        exit 0
        ;;
    --uninstall)
        uninstall_hooks
        exit 0
        ;;
    "")
        main
        ;;
    *)
        print_color $RED "❌ Unknown option: $1"
        echo ""
        show_help
        exit 1
        ;;
esac